name: Run Automation Scripts

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run System Health Monitor
        run: bash ./system_health_monitor.sh

      - name: Run Log & Alert Automation
        run: bash ./log_alert_automation.sh

      - name: Run Git Automation
        run: bash ./git_automation.sh
