name: Automation Portfolio Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-automation-scripts:
    name: Execute Bash Automation Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bash Environment
        run: |
          chmod +x *.sh

      - name: Run Log Automation Script
        run: |
          echo "Running log automation script..."
          ./log_alert_automation.sh || echo "⚠️ log_alert_automation.sh failed but continuing"

      - name: Run System Health Monitor Script
        run: |
          echo "Running system health monitor..."
          ./system_health_monitor.sh || echo "⚠️ system_health_monitor.sh failed but continuing"

      - name: Run Git Automation Script
        run: |
          echo "Running Git automation..."
          ./git_automation.sh || echo "⚠️ git_automation.sh failed but continuing"

      - name: Display Completed Logs
        run: |
          echo "===== Logs Folder Content ====="
          ls -l logs || echo "No logs folder found."
          echo "================================"
      - name: Display Completed Logs
        run: |
          echo "===== Logs Folder Content ====="
          ls -l logs || echo "No logs folder found."
          echo "================================"

      - name: Upload Logs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: logs/


